### ISSUE TITLE
Problem with xargs

### ISSUE THREAD

**Issue by rdebath** [Gandalf-/BrainBash#1]
The xargs command gets upset about quotes in it's input, you might try this to strip out the non-bf characters:

``` sh
sed -e ':l;$!{N;bl;};s/[^]<>+-.[]//g'
```

**Comment by Gandalf-** [comment]
Great catch! I decided to go with `xargs -0` instead of the sed approach but it's fixed as of https://github.com/Gandalf-/BrainBash/commit/9e5abb0269e684056533c0e09e3a74cab2b11dd1

Let me know if you come across anything else, or have any feature ideas!
